import { useEffect,useMemo,useState } from 'react';
import { api,type BootstrapData,type CatalogData,type DecisionMode } from './api';
import type { AuditInfo, DecisionTraceStep, FullRunResult, InsuranceProduct, StageResult, UserProfile } from '../shared/types';
import './styles.css';

const steps=[{key:'chat',label:'Chat 需求理解'},{key:'coupon',label:'优惠券决策'},{key:'recommendation',label:'产品推荐'},{key:'comparison',label:'产品比较'}] as const;
const typicalCaseIds=['C01','C07','C11','C12','C16'];
const typicalCaseNames:Record<string,string>={C01:'正常四阶段',C07:'信息缺失门禁',C11:'Voucher频控',C12:'PDP字段冲突',C16:'高车龄硬过滤'};
type StepKey=typeof steps[number]['key'];
const emptyStages:Record<StepKey,StageResult<any>|null>={chat:null,coupon:null,recommendation:null,comparison:null};
const modeLabels:Record<DecisionMode,string>={hybrid:'Hybrid 混合决策',rules_only:'Rules Only 纯规则',llm_only:'LLM Only 纯 LLM'};
const entityLabels:Record<string,string>={users:'用户画像',vehicles:'车辆',policies:'保单',behavior:'行为特征',voucher_batches:'Voucher Batch',voucher_instances:'Voucher Instance',user_vouchers:'User Voucher',product_definitions:'后端产品定义',product_cards:'Product Card 内容',pdp_pages:'PDP HTML 页面'};
const statusLabels:Record<string,string>={passed:'通过',failed:'未通过',warning:'需注意',info:'信息'};
const kindLabels:Record<string,string>={llm:'LLM节点',rule:'规则',filter:'硬过滤',score:'量化排序',validation:'校验',normalization:'归一化',fallback:'降级'};
const reasonLabels:Record<string,string>={MARKET_NOT_ELIGIBLE:'市场不符合',SEGMENT_NOT_ELIGIBLE:'用户分群不符合',RENEWAL_WINDOW_NOT_ELIGIBLE:'不在续保时间窗口',COUPON_NOT_ACTIVE:'活动未生效或已失效',CAMPAIGN_BUDGET_INSUFFICIENT:'活动预算不足',FREQUENCY_LIMIT_REACHED:'超过领取频控',NO_ELIGIBLE_PRODUCT_SCOPE:'没有适用产品',MAX_DISCOUNT_EXCEEDED:'折扣超过上限'};
const reasonText=(code:string|null|undefined)=>code?`${reasonLabels[code]??'未满足规则'}（${code}）`:'—';

function Json({value,compact=false}:{value:unknown;compact?:boolean}){return <pre className={compact?'compact-json':''}>{value===undefined||value===null?'尚未运行':JSON.stringify(value,null,2)}</pre>}

function TracePanel({trace}:{trace:DecisionTraceStep[]}){
  if(!trace.length)return <p className="empty">运行后显示可审计决策轨迹。</p>;
  const couponRules=trace.filter((item)=>item.step_id.startsWith('coupon-CPN-'));
  const productFilters=trace.filter((item)=>item.step_id.startsWith('filter-'));
  const compactIds=new Set([...couponRules,...productFilters].map((item)=>item.step_id));
  const card=(item:DecisionTraceStep,index:number)=><section className={`trace-step ${item.status}`} key={item.step_id}><div className="trace-summary"><span className="trace-index">{index+1}</span><span><b>{item.title}</b><small>{kindLabels[item.kind]??item.kind} · {item.reason_code??statusLabels[item.status]}</small></span><em>{statusLabels[item.status]??item.status}</em></div><p>{item.description}</p>{Array.isArray((item.input as any).checks)?<CheckTable inputChecks={(item.input as any).checks} outputChecks={(item.output as any).checks}/>:null}<details className="technical-details"><summary>查看节点技术详情</summary><div className="logic"><strong>处理逻辑</strong><code>{item.logic}</code></div><div className="trace-io"><div><strong>本节点使用字段</strong><Json value={item.input} compact/></div><div><strong>输出/判断</strong><Json value={item.output} compact/></div></div>{item.evidence?.length?<div className="evidence"><strong>证据</strong>{item.evidence.map((e,i)=><blockquote key={i}>{e}</blockquote>)}</div>:null}</details></section>;
  return <div className="trace-list">{couponRules.length?<div className="overview"><h3>Voucher 资格预筛总表</h3><table><thead><tr><th>Voucher</th><th>结果</th><th>首个失败原因</th></tr></thead><tbody>{couponRules.map((item)=><tr key={item.step_id}><td>{item.step_id.replace('coupon-','')}</td><td>{(item.output as any).eligible?'合资格':'排除'}</td><td>{reasonText((item.output as any).first_failure)}</td></tr>)}</tbody></table></div>:null}{productFilters.length?<div className="overview"><h3>产品硬过滤总表</h3><table><thead><tr><th>产品</th><th>在售</th><th>市场</th><th>车型</th><th>车龄</th><th>Voucher</th><th>结果</th></tr></thead><tbody>{productFilters.map((item)=>{const checks=(item.input as any).checks??[];return <tr key={item.step_id}><td>{item.step_id.replace('filter-','')}</td>{checks.map((x:any)=><td key={x.label}>{x.pass?'通过':'不通过'}</td>)}<td>{(item.output as any).eligible?'进入排序':'排除'}</td></tr>})}</tbody></table></div>:null}{trace.filter((item)=>!compactIds.has(item.step_id)).map(card)}{compactIds.size?<details className="technical-bundle"><summary>查看逐项校验明细（{compactIds.size}项）</summary>{trace.filter((item)=>compactIds.has(item.step_id)).map(card)}</details>:null}</div>;
}

function CheckTable({inputChecks,outputChecks=[]}:{inputChecks:any[];outputChecks?:any[]}){return <div className="check-table table-wrap"><table><thead><tr><th>校验项</th><th>实际值</th><th>资格要求</th><th>结果</th></tr></thead><tbody>{inputChecks.map((check,index)=>{const result=outputChecks.find((x:any)=>x.rule===check.rule);return <tr key={check.rule??index}><td>{check.label??check.rule}</td><td>{typeof check.actual==='object'?JSON.stringify(check.actual):String(check.actual)}</td><td>{typeof check.expected==='object'?JSON.stringify(check.expected):String(check.expected)}</td><td>{(result?.pass??check.pass)?'通过':`不通过（${result?.reason_code??'未满足'}）`}</td></tr>})}</tbody></table></div>}

function ProductCards({ids,catalog,onOpen}:{ids:string[];catalog:CatalogData;onOpen:(product:InsuranceProduct)=>void}){
  return <section className="recommend-shell"><div className="recommend-heading"><div><span>PERSONALISED MOTOR SHELF</span><h2>为你推荐 · Recommended</h2></div><p>后端按 Product Definition 决策，界面再用 product_id 取得卡片内容</p></div><div className="product-cards">{ids.map((id)=>{const p=catalog.product_definitions.find((x)=>x.product_id===id);const content=catalog.product_cards.find((x)=>x.product_id===id);if(!p||!content)return null;return <button className="product-card" onClick={()=>onOpen(p)} key={id}><span className="product-avatar" style={{background:content.card.accent}}>{content.card.avatar}</span><span className="product-main">{content.card.badge&&<i>{content.card.badge}</i>}<b>{p.product_name}</b><small>{p.insurer}</small><span>✓ {content.card.selling_points[0]}</span><span>✓ {content.card.selling_points[1]}</span></span><span className="price"><small>From</small><strong>MYR {p.annual_premium}</strong><em>/ year</em><u>打开独立 PDP →</u></span></button>})}</div></section>;
}

function PdpModal({product,profile,catalog,onClose}:{product:InsuranceProduct;profile:UserProfile;catalog:CatalogData;onClose:()=>void}){
  const content=catalog.product_cards.find((x)=>x.product_id===product.product_id);const route=content?.pdp_route??`/pdp.html?product_id=${product.product_id}`;
  return <div className="modal-backdrop" onClick={onClose}><article className="pdp-modal pdp-page-modal" onClick={(e)=>e.stopPropagation()}><div className="modal-toolbar"><div><b>{product.product_name}</b><small>独立 HTML 页面 · 当前用户 {profile.user_id} 仅用于本次决策，不写入 PDP</small></div><a href={route} target="_blank" rel="noreferrer">在新窗口打开</a><button className="modal-close" onClick={onClose}>×</button></div><iframe title={`${product.product_name} PDP`} src={route}/></article></div>;
}

const comparisonFieldLabels:Record<string,string>={annual_premium:'年保费',sum_insured:'保额',deductible:'免赔额',roadside_assistance:'道路救援',term_and_waiting_period:'保障期/等待期',claim_channel_and_documents:'理赔渠道与材料',vehicle_eligibility:'车辆资格','coverage.collision':'碰撞保障','coverage.theft':'盗抢保障','coverage.flood':'水浸保障','coverage.fire':'火灾保障','coverage.natural_disaster':'自然灾害保障','coverage.third_party':'第三者责任','coverage.personal_accident':'个人意外保障'};
const displayNotStated=(fields:string[]|undefined)=>(fields??[]).map((field)=>comparisonFieldLabels[field]??field).join('、')||'无';
function ComparisonTable({result}:{result:any}){if(!result?.products?.length)return null;return <div className="table-wrap comparison-table"><table><thead><tr><th>字段</th>{result.products.map((p:any)=><th key={p.product_id}>{p.product_name}</th>)}</tr></thead><tbody>{[['年保费',(p:any)=>p.annual_premium],['优惠后保费',(p:any)=>p.premium_after_coupon],['保额',(p:any)=>p.sum_insured],['免赔额',(p:any)=>p.deductible],['水浸',(p:any)=>p.coverage.flood],['第三者责任',(p:any)=>p.coverage.third_party],['个人意外',(p:any)=>p.coverage.personal_accident],['道路救援',(p:any)=>p.roadside_assistance],['PDP未披露字段',(p:any)=>displayNotStated(p.not_stated_fields)],['字段冲突',(p:any)=>p.conflicts.join(', ')||'无']].map(([label,get])=><tr key={label as string}><th>{label as string}</th>{result.products.map((p:any)=><td key={p.product_id}>{String((get as any)(p))}</td>)}</tr>)}</tbody></table></div>}

function AuditFooter({audit}:{audit:AuditInfo|null}){if(!audit)return <footer>审计信息会在运行后显示。</footer>;return <footer><span>运行ID：{audit.run_id}</span><span>模式：{modeLabels[audit.mode]}</span><span>Schema：{audit.schema_valid?'通过':'失败'}</span><span>重试：{audit.retry_count}</span><span>人工核对：{audit.manual_review?'是':'否'}</span></footer>}

function DatabaseExplorer({catalog}:{catalog:CatalogData}){
  const [entity,setEntity]=useState<keyof CatalogData['dictionary']>('users');const [selected,setSelected]=useState(0);
  const records=useMemo(()=>{if(entity==='vehicles')return catalog.users.flatMap((u)=>u.vehicles.map((x)=>({user_id:u.user_id,...x})));if(entity==='policies')return catalog.users.flatMap((u)=>u.policies.map((x)=>({user_id:u.user_id,...x})));if(entity==='behavior')return catalog.users.map((u)=>({user_id:u.user_id,...u.behavior_features}));return (catalog as any)[entity]??[]},[catalog,entity]);
  const record=records[Math.min(selected,Math.max(0,records.length-1))];const fields=catalog.dictionary[entity];
  const choose=(key:keyof CatalogData['dictionary'])=>{setEntity(key);setSelected(0)};
  return <section className="database"><div className="database-intro"><div><span>FICTIONAL DATA EXPLORER</span><h2>数据库与字段字典</h2><p>展示 PoC 实际使用的内存数据库。所有身份、车辆、保单、券和产品均为虚构或脱敏。</p></div><div className="db-summary">{Object.entries(catalog.summary).filter(([,v])=>typeof v==='number').map(([k,v])=><div key={k}><b>{v}</b><small>{k}</small></div>)}</div></div>
    <nav className="entity-tabs">{Object.keys(catalog.dictionary).map((key)=><button className={entity===key?'active':''} onClick={()=>choose(key as keyof CatalogData['dictionary'])} key={key}>{entityLabels[key]} <span>{key==='vehicles'?catalog.summary.vehicles:key==='policies'?catalog.summary.policies:(catalog as any)[key]?.length??catalog.users.length}</span></button>)}</nav>
    <div className="db-layout"><aside><h3>{entityLabels[entity]}记录</h3>{records.map((item:any,index:number)=><button className={selected===index?'active':''} onClick={()=>setSelected(index)} key={index}><b>{item.user_id??item.product_id??item.coupon_id??item.voucher_instance_id??item.user_voucher_id??item.pdp_id??`#${index+1}`}</b><small>{item.product_name??item.batch_name??item.model??item.policy_name??item.status??item.tags?.[0]??''}</small></button>)}</aside><article><div className="record-head"><div><span>RECORD {selected+1}/{records.length}</span><h3>{entityLabels[entity]}详情</h3></div><span className="fictional-badge">FICTIONAL / MASKED</span></div>{entity==='users'&&record?<UserRecord user={record}/>:entity==='product_definitions'&&record?<ProductRecord product={record}/>:entity==='product_cards'&&record?<ProductCardRecord content={record} catalog={catalog}/>:entity==='pdp_pages'&&record?<PdpPageRecord page={record}/>:<Json value={record}/>}</article></div>
    <section className="dictionary"><h3>{entityLabels[entity]}字段释义</h3><div className="table-wrap"><table><thead><tr><th>字段</th><th>含义</th><th>示例</th><th>来源</th><th>LLM 权限</th></tr></thead><tbody>{fields.map((x)=><tr key={x.field}><td><code>{x.field}</code></td><td>{x.meaning}</td><td>{x.example}</td><td>{x.source}</td><td><span className={`access ${x.llm_access}`}>{x.llm_access}</span></td></tr>)}</tbody></table></div></section>
  </section>;
}

function UserRecord({user}:{user:UserProfile}){return <div className="record-sections"><section><h4>Profile Snapshot</h4><Json value={{user_id:user.user_id,profile_snapshot_id:user.profile_snapshot_id,market:user.market,segment:user.segment,generated_at:user.generated_at}} compact/></section><section><h4>Demographics（PII未调取）</h4><Json value={user.demographics} compact/></section><section><h4>Vehicles</h4><Json value={user.vehicles} compact/></section><section><h4>Policies</h4><Json value={user.policies} compact/></section><section><h4>Behavior Features</h4><Json value={user.behavior_features} compact/></section><section><h4>Privacy Contract</h4><Json value={user.privacy} compact/></section></div>}
function ProductRecord({product}:{product:InsuranceProduct}){return <div className="record-sections"><section><h4>推荐与承保资格规则（后端）</h4><p className="section-help">Eligibility 指能否投保的硬条件；不满足时产品直接被过滤。</p><Json value={{product_id:product.product_id,market:product.market,active:product.active,eligible_vehicle_types:product.eligible_vehicle_types,maximum_vehicle_age_years:product.maximum_vehicle_age_years}} compact/></section><section><h4>匹配与排序特征（后端）</h4><p className="section-help">Coverage 是标准化检索标签，用于匹配需求；正式保障结论仍须从 PDP 抽取。</p><Json value={{annual_premium:product.annual_premium,currency:product.currency,coverage_tags:product.coverage_tags,roadside_assistance:product.roadside_assistance,claim_channel:product.claim_channel,coupon_ids:product.coupon_ids,pdp_id:product.pdp_id}} compact/></section></div>}
function ProductCardRecord({content,catalog}:{content:CatalogData['product_cards'][number];catalog:CatalogData}){const product=catalog.product_definitions.find((x)=>x.product_id===content.product_id);return <div className="record-sections"><section><h4>前端推荐卡片</h4><div className="mini-product"><span className="product-avatar" style={{background:content.card.accent}}>{content.card.avatar}</span><div><b>{product?.product_name}</b><small>{content.card.selling_points.join(' · ')}</small></div><strong>MYR {product?.annual_premium}</strong></div></section><section><h4>CMS 内容与页面关联</h4><Json value={content} compact/><a className="open-pdp" href={content.pdp_route} target="_blank" rel="noreferrer">打开独立 PDP 页面 →</a></section></div>}
function PdpPageRecord({page}:{page:CatalogData['pdp_pages'][number]}){return <div className="pdp-record"><div className="pdp-record-meta"><Json value={{pdp_id:page.pdp_id,product_id:page.product_id,route:page.route,content_type:page.content_type,cms_version:page.cms_version}} compact/><a className="open-pdp" href={page.route} target="_blank" rel="noreferrer">在新窗口打开完整 PDP →</a></div><iframe title={`${page.product_id} PDP preview`} src={page.route}/></div>}

const percent=(value:number)=>`${(value*100).toFixed(1)}%`;
function exportEvaluation(result:any){
  const content=JSON.stringify(result,null,2);const blob=new Blob([content],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');
  const stamp=String(result.generated_at??new Date().toISOString()).replace(/[:.]/g,'-');link.href=url;link.download=`nara-evaluation-${result.scope??'batch'}-${stamp}.json`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);
}
function EvaluationPanel({busy,result,scope,onRun}:{busy:boolean;result:any;scope:'typical'|'all';onRun:(value:'typical'|'all')=>void}){
  return <section className="evaluation-page"><div className="evaluation-intro"><div><span>FOUR-STAGE BATCH EVALUATION</span><h2>三模式批量达标率评估</h2><p>这里不用于观察单次推理。固定重复5次，用同一批输入分别评估 Hybrid / Rules Only / LLM Only。</p></div></div>
    <div className="batch-options"><article className={scope==='typical'?'selected':''}><span>推荐先运行</span><h3>典型集 · 75次</h3><p>5个典型案例 × 3种模式 × 每例重复5次</p><dl><div><dt>完整管线</dt><dd>75次</dd></div><div><dt>预计Gemini请求</dt><dd>约150–175次</dd></div></dl><button className="primary" onClick={()=>onRun('typical')} disabled={busy}>{busy&&scope==='typical'?'正在评估75次…':'运行典型集评估'}</button></article><article className={scope==='all'?'selected':''}><span>正式全量</span><h3>全量集 · 300次</h3><p>20个案例 × 3种模式 × 每例重复5次</p><dl><div><dt>完整管线</dt><dd>300次</dd></div><div><dt>预计Gemini请求</dt><dd>约600–700次</dd></div></dl><button onClick={()=>onRun('all')} disabled={busy}>{busy&&scope==='all'?'正在评估300次…':'运行全量评估'}</button></article></div>
    <p className="batch-warning">真实Gemini会按低于15 RPM的速度逐次调用API；75次通常需要较长时间。若发生Mock回退，结果会明确标为“不适合作为真实LLM结论”。</p>
    <div className="metric-rules"><b>精简判分：</b><span>Chat关键字段正确</span><span>Voucher结论正确</span><span>推荐首位可接受且不越硬规则</span><span>比较关键字段有据可查</span><strong>全链通过 = 同次四项全通过</strong></div>
    {!result?<div className="evaluation-empty"><h3>批量结果不是预制的</h3><p>选择上方75次或300次评估后，系统才会执行完整管线并计算达标率。单次输入输出请回到“决策演示”。</p></div>:<><section className="evaluation-summary"><div className={`evaluation-validity ${result.real_llm_result_valid?'valid':'invalid'}`}>{result.real_llm_result_valid?'真实LLM评估有效：本批次未发生Mock回退':`本批次发生 ${result.provider_fallback_runs} 次Mock回退，不应作为真实LLM结论`}</div><div className="evaluation-result-head"><div><h3>本次实测结果 · {result.execution_count}次</h3><p>{result.test_case_count}个案例 · {result.profile_count}个画像 · 每例每模式固定重复{result.repeats_per_case}次 · {result.llm_provider}</p><small>{result.note}</small></div><button className="primary export-button" onClick={()=>exportEvaluation(result)}>导出本次评估 JSON</button></div><div className="table-wrap"><table><thead><tr><th>模式</th><th>Chat</th><th>Voucher</th><th>产品推荐</th><th>产品比较</th><th>全链通过</th><th>硬规则违规</th><th>无来源字段</th><th>Mock回退运行</th></tr></thead><tbody>{result.modes.map((x:any)=><tr key={x.mode}><th>{modeLabels[x.mode as DecisionMode]}</th><td>{percent(x.chat_pass_rate)}</td><td>{percent(x.voucher_pass_rate)}</td><td>{percent(x.recommendation_pass_rate)}</td><td>{percent(x.comparison_pass_rate)}</td><td><b>{percent(x.full_chain_pass_rate)}</b></td><td className={x.hard_condition_violations?'bad-cell':'good-cell'}>{x.hard_condition_violations}</td><td className={x.ungrounded_pdp_fields?'bad-cell':'good-cell'}>{x.ungrounded_pdp_fields}</td><td className={x.provider_fallback_runs?'bad-cell':'good-cell'}>{x.provider_fallback_runs}</td></tr>)}</tbody></table></div></section>
    <section className="case-evidence"><h3>逐案例：标准答案、实际输出与差异</h3>{result.case_results.map((item:any,index:number)=><details key={item.case_id} open={result.case_results.length===1}><summary><span>{item.typical?`典型案例 ${typicalCaseIds.indexOf(item.case_id)+1}`:`其他案例 ${index+1}`} · {item.case_id} · {item.case_name} · {item.profile_id}</span><small>{Object.values(item.modes).every((x:any)=>x.full_chain_pass_rate===1)?'三模式均全链通过':'存在差异，展开查看'}</small></summary><div className="expected-grid"><section><h4>Chat 标准</h4><Json value={item.expected.chat} compact/></section><section><h4>Voucher 标准</h4><Json value={item.expected.voucher} compact/></section><section><h4>推荐标准</h4><Json value={item.expected.recommendation} compact/></section><section><h4>比较标准</h4><Json value={item.expected.comparison} compact/></section></div><div className="case-mode-grid">{Object.entries(item.modes).map(([modeKey,value]:[string,any])=><section key={modeKey}><h4>{modeLabels[modeKey as DecisionMode]}</h4><div className="stage-badges"><span>Chat {percent(value.chat_pass_rate)}</span><span>券 {percent(value.voucher_pass_rate)}</span><span>推荐 {percent(value.recommendation_pass_rate)}</span><span>比较 {percent(value.comparison_pass_rate)}</span><b>全链 {percent(value.full_chain_pass_rate)}</b></div>{value.mismatches.length?<ul className="mismatches">{value.mismatches.map((message:string)=><li key={message}>{message}</li>)}</ul>:<p className="all-pass">所有最小验收项均通过</p>}<details className="actual-output"><summary>查看本次实际输出摘要</summary><Json value={value.sample_actual} compact/></details></section>)}</div></details>)}</section></>}
  </section>;
}

export default function App(){
  const [data,setData]=useState<BootstrapData|null>(null);const [catalog,setCatalog]=useState<CatalogData|null>(null);const [view,setView]=useState<'demo'|'database'|'evaluation'>('demo');
  const [caseId,setCaseId]=useState('C01');const [mode,setMode]=useState<DecisionMode>('hybrid');const [evaluationScope,setEvaluationScope]=useState<'typical'|'all'>('typical');const [message,setMessage]=useState('');const [active,setActive]=useState(0);const [stages,setStages]=useState(emptyStages);const [audit,setAudit]=useState<AuditInfo|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [evaluation,setEvaluation]=useState<any>(null);const [pdpProduct,setPdpProduct]=useState<InsuranceProduct|null>(null);
  const selectedCase=useMemo(()=>data?.cases.find((item)=>item.id===caseId),[data,caseId]);const profile=useMemo(()=>data?.users.find((u)=>u.user_id===selectedCase?.profile_id),[data,selectedCase]);
  useEffect(()=>{Promise.all([api.bootstrap(),api.catalog()]).then(([base,cat])=>{setData(base);setCatalog(cat);setMessage(base.cases[0].message)}).catch((e)=>setError(e.message));},[]);
  const selectCase=(id:string)=>{const item=data?.cases.find((x)=>x.id===id);setCaseId(id);if(item)setMessage(item.message);setStages(emptyStages);setAudit(null);setEvaluation(null);setError('')};
  const runAll=async()=>{if(!selectedCase)return;setBusy(true);setError('');try{const result=await api.fullRun({case_id:caseId,mode,message,profile_id:selectedCase.profile_id});setStages(result.stages);setAudit(result.audit)}catch(e){setError(String(e))}finally{setBusy(false)}};
  const runCurrent=async()=>{if(!selectedCase)return;setBusy(true);setError('');const key=steps[active].key;try{let result:StageResult<any>;if(key==='chat')result=await api.chat({message,mode,mock_fault:selectedCase.mock_fault});else if(key==='coupon'){if(!stages.chat?.output)throw new Error('请先运行 Chat 阶段');result=await api.coupon({need:stages.chat.output,profile_id:selectedCase.profile_id,mode})}else if(key==='recommendation'){if(!stages.chat?.output||!stages.coupon?.output)throw new Error('请先运行 Chat 和优惠券阶段');result=await api.recommendation({need:stages.chat.output,coupon:stages.coupon.output,profile_id:selectedCase.profile_id,mode})}else{if(!stages.chat?.output)throw new Error('请先运行 Chat 阶段');if(!stages.recommendation?.output)throw new Error('请先运行 Chat 和产品推荐阶段');const ids=stages.recommendation.output.recommended_products.map((x:any)=>x.product_id);result=await api.comparison({need:stages.chat.output,selected_product_ids:ids,discount:stages.coupon?.output?.discount_value??0,mode})}setStages((current)=>({...current,[key]:result}))}catch(e){setError(String(e))}finally{setBusy(false)}};
  const compare=async(scope:'typical'|'all')=>{if(scope==='all'&&!window.confirm('全量评估将执行300次完整管线，并可能产生约600–700次Gemini请求。确认继续吗？'))return;setEvaluationScope(scope);setEvaluation(null);setBusy(true);setError('');try{setEvaluation(await api.evaluation(5,scope,caseId))}catch(e){setError(String(e))}finally{setBusy(false)}};const reset=()=>{if(selectedCase)setMessage(selectedCase.message);setStages(emptyStages);setAudit(null);setError('');setActive(0)};
  if(!data||!catalog||!profile)return <main className="loading">正在读取虚构数据库… {error}</main>;const current=stages[steps[active].key];const recommendedIds=stages.recommendation?.output?.recommended_products?.map((x:any)=>x.product_id)??[];
  return <main><header><div><p className="eyebrow">SPEC-DRIVEN PROOF OF CONCEPT · V5 可替换 LLM 验证 / PUBLIC MOCK DEMO</p><h1>Nara AI 保险助手</h1><p>多用户、多券批次、多产品 · 全链路可审计</p></div><div className="top-nav"><button className={view==='demo'?'active':''} onClick={()=>setView('demo')}>决策演示</button><button className={view==='evaluation'?'active':''} onClick={()=>setView('evaluation')}>三模式评估</button><button className={view==='database'?'active':''} onClick={()=>setView('database')}>数据库与字段</button></div><div className="privacy">模型：{data.llm_provider}<br/>公开版使用 Mock；仅使用虚构/脱敏数据，敏感身份字段不调取、不进入 LLM</div></header>
  {view==='database'?<DatabaseExplorer catalog={catalog}/>:view==='evaluation'?<><EvaluationPanel busy={busy} result={evaluation} scope={evaluationScope} onRun={compare}/>{error&&<div className="error">{error}</div>}</>:<>
    <section className="toolbar"><label>测试案例（共20个）<select value={caseId} onChange={(e)=>selectCase(e.target.value)}><optgroup label="典型案例（5个）">{data.cases.filter((item)=>typicalCaseIds.includes(item.id)).map((item,index)=><option key={item.id} value={item.id}>典型案例 {index+1} · {item.id} · {typicalCaseNames[item.id]} · {item.profile_id}</option>)}</optgroup><optgroup label="其他可选案例（15个）">{data.cases.filter((item)=>!typicalCaseIds.includes(item.id)).map((item)=><option key={item.id} value={item.id}>{item.id} · {item.name} · {item.profile_id}</option>)}</optgroup></select></label><label>决策模式<select value={mode} onChange={(e)=>setMode(e.target.value as DecisionMode)}>{Object.entries(modeLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><div className="actor"><span>当前扮演用户</span><b>{profile.user_id} · {profile.vehicle_type} · {profile.segment}</b><small>{profile.behavior_features.tags.slice(0,2).join(' · ')}</small></div><div className="actions"><button className="primary" onClick={runAll} disabled={busy}>运行一次四阶段</button><button onClick={reset} disabled={busy}>重置</button><details className="advanced-actions"><summary>高级操作</summary><button onClick={runCurrent} disabled={busy}>仅运行当前阶段</button></details></div></section>
    <div className="single-run-note"><strong>单次决策演示：</strong>用于查看当前案例、当前模式的一次完整输入、处理过程和输出；这里不计算达标率。</div><nav className="stepper">{steps.map((step,index)=><button key={step.key} className={active===index?'active':''} onClick={()=>setActive(index)}><span>{stages[step.key]?.schema_valid?'✓':index+1}</span>{step.label}</button>)}</nav>{error&&<div className="error">{error}</div>}{busy&&<div className="notice">正在运行规则、Gemini与审计节点…</div>}
    <section className="ranking-note"><strong>产品排序：</strong>保障匹配 60% ＋ 优惠后价格/预算 40%；使用场景和服务信息只展示，不做无依据打分。</section>
    <section className="stage-grid"><article><h2>本阶段完整输入</h2>{active===0?<textarea value={message} onChange={(e)=>setMessage(e.target.value)} rows={10}/>:<Json value={current?.input}/>}<p className="hint">案例：{selectedCase?.category} · Profile Snapshot：{profile.profile_snapshot_id}</p></article><article className="brain"><div className="brain-title"><div><span>DECISION BRAIN</span><h2>输入与输出之间发生了什么</h2></div><small>可审计摘要，不展示隐藏思维链</small></div><TracePanel trace={current?.trace??[]}/></article><article><h2>结构化 JSON 输出</h2><Json value={current?.output}/></article></section>
    {active===2&&recommendedIds.length>0&&<ProductCards ids={recommendedIds} catalog={catalog} onOpen={setPdpProduct}/>} {active===3&&<ComparisonTable result={current?.output}/>} 
    <AuditFooter audit={audit}/>
  </>}{pdpProduct&&<PdpModal product={pdpProduct} profile={profile} catalog={catalog} onClose={()=>setPdpProduct(null)}/>}</main>;
}
